erDiagram
    websockets_statistics_entries {
        increments id
        string app_id
        integer peak_connection_count
        integer websocket_message_count
        integer api_message_count
    }
    users {
        string name
        string email
        string mobile
        timestamp email_verified_at
        string password
        string buyer_name
        boolean isGreyManager
        boolean isAdmin
        boolean isAuctionManager
        boolean isBuyer
        boolean isSeller
        boolean showSellerDetails
        string device_token
    }
    password_resets {
        string email
        string token
        timestamp created_at
    }
    Unknown {
        text two_factor_secret
        text two_factor_recovery_codes
        dropColumn two_factor_secret
    }
    failed_jobs {
        string uuid
        text connection
        text queue
        longText payload
        longText exception
        timestamp failed_at
    }
    discounts {
        bigInteger credit_by
        float discount
        bigInteger created_by
        bigInteger updated_by
    }
    master_discounts {
        string discount
        string grace_period
        enum is_active
        bigInteger created_by
        bigInteger updated_by
    }
    buyers {
        bigInteger user_id
        foreign user_id
        foreignId user_id
    }
    grades {
        string name
        string description
        enum is_active
        bigInteger created_by
        bigInteger updated_by
    }
    sellers {
        bigInteger user_id
        enum seller_type
        foreign user_id
        foreignId user_id
    }
    quality {
        string name
        string description
        enum is_active
        bigInteger created_by
        bigInteger updated_by
    }
    lots {
        bigInteger seller_id
        string name
        string description
        enum status
        bigInteger warehouse_id
        string type
        string subtype
        bigInteger liter_weight
        bigInteger color_id
        double net_weight
        double sample_weight
        double moisture_content
        boolean clean_lot
        bigInteger time_limit
        string image_url
        string currency
        string nick_name
        bigInteger quote_price
        bigInteger control_price
        bigInteger sold_price
        date sold_date
        bigInteger gunny_bags
        bigInteger plastic_rate
        bigInteger loading_rate
        bigInteger gunny_bags_rate
        bigInteger credit_by
        foreignId seller_id
        foreign seller_id
    }
    auctions {
        bigInteger auction_id
        string name
        string description
        datetime schedule_start
        datetime schedule_end
        enum status
        bigInteger total_lots
        bigInteger lots_sold
        bigInteger lots_unsold
        bigInteger lots_withdrawn
        bigInteger created_by
        bigInteger updated_by
        boolean visibility
    }
    auction_lots {
        bigInteger auction_id
        bigInteger lot_id
        bigInteger lot_name
        bigInteger quote_price
        bigInteger control_price
        bigInteger highest_bid_price
        bigInteger sold_price
        enum status
        bigInteger buyer_id
        bigInteger created_by
        bigInteger updated_by
        foreign buyer_id
        foreign lot_id
        foreign auction_id
        datetime auction_start
        datetime auction_end
        bigInteger buyer_id
        foreignId lot_id
        foreignId auction_id
    }
    address {
        bigInteger owner_id
        string address1
        string address2
        string address3
        bigInteger pincode
        string district
        string state
        string country
        double lat
        double lng
        string is_active
    }
    admins {
        bigInteger user_id
        foreign user_id
        foreignId user_id
    }
    auctioneers {
        bigInteger user_id
        foreign user_id
        foreignId user_id
    }
    plantation {
        string name
        bigInteger address_id
        foreign address_id
        foreignId address_id
        bigInteger seller_id
        foreign seller_id
        foreignId seller_id
    }
    lot_gradings {
        string grade
        string quality
        double value_mg
        double value_percentage
        bigInteger created_by
        bigInteger updated_by
        bigInteger lot_id
        foreign lot_id
        bigInteger grade_id
        foreign grade_id
        bigInteger quality_id
        foreign quality_id
        foreignId lot_id
    }
    gst {
        bigInteger user_id
        string gst_number
        string details
        bigInteger address_id
        enum is_active
        foreign user_id
        foreign address_id
        foreignId user_id
        foreignId address_id
    }
    buyer_auto_bids {
        bigInteger buyer_id
        bigInteger auction_lot_id
        bigInteger starting_quote_price
        bigInteger upper_quote_price
        double increment
        foreign buyer_id
        foreign auction_lot_id
        foreignId buyer_id
        foreignId auction_lot_id
    }
    color {
        string name
        string description
        enum is_active
        bigInteger created_by
        bigInteger updated_by
    }
    bidding {
        bigInteger auction_lot_id
        bigInteger buyer_id
        bigInteger bid_price
        time bidding_time
        string bidding_mode
        enum status
        foreign auction_lot_id
        foreign buyer_id
        foreignId auction_lot_id
        foreignId buyer_id
    }
    lot_type {
        string name
    }
    lot_subtype {
        string name
        string type
    }
    grade_template {
        string row_name
        string subtype
    }
    jobs {
        bigIncrements id
        string queue
        longText payload
        unsignedTinyInteger attempts
        unsignedInteger reserved_at
        unsignedInteger available_at
        unsignedInteger created_at
    }
    sessions {
        string id
        foreignId user_id
        string ip_address
        text user_agent
        text payload
        integer last_activity
    }
    cache {
        string key
        mediumText value
        integer expiration
    }
    warehouses {
        bigInteger seller_id
        string name
        bigInteger commission
        enum is_active
    }
    notifications {
        uuid id
        string type
        morphs notifiable
        text data
        timestamp read_at
    }
    support {
        bigInteger user_id
        string name
        string email
        bigInteger phone
        string title
        longtext description
        enum status
    }
    terms {
        longtext terms
    }
    bidding_history {
        bigInteger auction_lot_id
        bigInteger buyer_id
        bigInteger bid_price
        time bidding_time
        string bidding_mode
        enum status
        foreign auction_lot_id
        foreign buyer_id
        foreignId auction_lot_id
        foreignId buyer_id
    }
    versions {
        string version_number
        boolean update_type
    }
    cache_locks {
        string key
        string owner
        integer expiration
    }
    wishlist {
        bigInteger user_id
        bigInteger auction_id
        bigInteger auction_lot_id
    }
    buyers ||--o{ users : "user_id"
    sellers ||--o{ users : "user_id"
    lots ||--o{ sellers : "seller_id"
    auction_lots ||--o{ buyers : "buyer_id"
    auction_lots ||--o{ lots : "lot_id"
    auction_lots ||--o{ auctions : "auction_id"
    admins ||--o{ users : "user_id"
    auctioneers ||--o{ users : "user_id"
    plantation ||--o{ address : "address_id"
    plantation ||--o{ sellers : "seller_id"
    lot_gradings ||--o{ lots : "lot_id"
    lot_gradings ||--o{ grades : "grade_id"
    lot_gradings ||--o{ quality : "quality_id"
    gst ||--o{ users : "user_id"
    gst ||--o{ address : "address_id"
    buyer_auto_bids ||--o{ buyers : "buyer_id"
    buyer_auto_bids ||--o{ auction_lots : "auction_lot_id"
    bidding ||--o{ auction_lots : "auction_lot_id"
    bidding ||--o{ buyers : "buyer_id"
    bidding_history ||--o{ auction_lots : "auction_lot_id"
    bidding_history ||--o{ buyers : "buyer_id"
